services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./db.csv:/app/db.csv
      - ./db_meal.csv:/app/db_meal.csv
    restart: unless-stopped
    environment:
      - FLASK_ENV=production

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiZmRkNGRiNmY1ODc4MTE0OWVhMzg2YjNkMTcwOWNiNDciLCJ0IjoiZTU4MjcwMzgtZTY1My00Y2I3LWJlN2QtMWI1OWNhZWNkMzIwIiwicyI6IllqRTBabUUwWlRNdFpUZ3hNaTAwTURVNUxXSTBPV1l0WkRnMllXWmpaamhoTnpWaiJ9
    depends_on:
      - app
    restart: unless-stopped
